[package]
name = "pgp-words"
version = "1.1.0"
authors = ["Tim Marinin <mt@marinintim.com>"]
license = "MIT"
description = "Library to convert bytes to PGP words and back"
homepage = "https://github.com/marinintim/pgp-words"

[dependencies]
